version: '3.8'

services:
  mysql-service:
    image: mysql:8.4
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - net-wp
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 20s
      retries: 10
      start_period: 30s

  wordpress-service:
    image: wordpress:6.0
    container_name: wordpress_container
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql-service:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin123
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - wordpress-vol:/var/www/html
    networks:
      - net-wp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 20s
      timeout: 20s
      retries: 10
      start_period: 50s
    restart: always
    depends_on:
      mysql-service:
        condition: service_healthy

volumes:
  mysql-data:
  wordpress-vol:

networks:
  net-wp:
    driver: bridge
